//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDENCIAL
    {
        public decimal ID_CREDENCIAL { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime FEC_CADUCIDAD { get; set; }
        public decimal ID_STS { get; set; }
        public string RUT { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
