//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_ORD_COMP
    {
        public decimal ID_DET_ORD_COMP { get; set; }
        public decimal COD_PRODUCTO { get; set; }
        public decimal ID_ORDEN_COMPRA { get; set; }
        public decimal CANTIDAD { get; set; }
    
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
