//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIR_DESPACHO
    {
        public DIR_DESPACHO()
        {
            this.DIR_DES_CLI = new HashSet<DIR_DES_CLI>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal COD_DIR { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<DIR_DES_CLI> DIR_DES_CLI { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
