//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIR_DES_CLI
    {
        public decimal ID_DES { get; set; }
        public decimal COD_DIR { get; set; }
        public string RUT { get; set; }
    
        public virtual DIR_DESPACHO DIR_DESPACHO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
