//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CREDENCIAL> CREDENCIAL { get; set; }
        public DbSet<DET_ORD_COMP> DET_ORD_COMP { get; set; }
        public DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public DbSet<DIR_DES_CLI> DIR_DES_CLI { get; set; }
        public DbSet<DIR_DESPACHO> DIR_DESPACHO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
        public DbSet<FAMILIA_PRODUCTO> FAMILIA_PRODUCTO { get; set; }
        public DbSet<GENERO> GENERO { get; set; }
        public DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROMOCION> PROMOCION { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TIPO_COMPROBANTE> TIPO_COMPROBANTE { get; set; }
        public DbSet<TIPO_ENTREGA> TIPO_ENTREGA { get; set; }
        public DbSet<TIPO_MONEDA> TIPO_MONEDA { get; set; }
        public DbSet<TIPO_PAGO> TIPO_PAGO { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<USUARIO_VENTA> USUARIO_VENTA { get; set; }
        public DbSet<VENT_TIP_PAGO> VENT_TIP_PAGO { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    }
}
