//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        public ORDEN_COMPRA()
        {
            this.DET_ORD_COMP = new HashSet<DET_ORD_COMP>();
        }
    
        public decimal ID_ORDEN_COMPRA { get; set; }
        public System.DateTime FEC_EMISION { get; set; }
    
        public virtual ICollection<DET_ORD_COMP> DET_ORD_COMP { get; set; }
    }
}
