//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DET_ORD_COMP = new HashSet<DET_ORD_COMP>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public decimal COD_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FEC_VENCIMIENTO { get; set; }
        public decimal STOCK { get; set; }
        public decimal STOCK_CRITICO { get; set; }
        public decimal PRECIO { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] IMAGEN { get; set; }
        public decimal ID_TIP_PROD { get; set; }
        public string RUT_EMP { get; set; }
        public decimal ID_STS { get; set; }
        public decimal ID_PROVEEDOR { get; set; }
        public Nullable<decimal> ID_PROMO { get; set; }
    
        public virtual ICollection<DET_ORD_COMP> DET_ORD_COMP { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual PROMOCION PROMOCION { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
    }
}
