//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public PROMOCION()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_PROMO { get; set; }
        public string NAME_PROMO { get; set; }
        public System.DateTime FEC_INICIO { get; set; }
        public System.DateTime FEC_TERMINO { get; set; }
        public Nullable<decimal> PORC_DESC { get; set; }
        public Nullable<decimal> MONTO_PROMO { get; set; }
        public decimal ID_STS { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
