//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string RUT_PROVEEDOR { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string NOMBRE { get; set; }
        public decimal CELULAR { get; set; }
        public string CORREO { get; set; }
        public decimal ID_COMUNA { get; set; }
        public decimal ID_STS { get; set; }
        public decimal ID_RUBRO { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
