//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CREDENCIAL = new HashSet<CREDENCIAL>();
            this.DIR_DES_CLI = new HashSet<DIR_DES_CLI>();
            this.USUARIO_VENTA = new HashSet<USUARIO_VENTA>();
        }
    
        public string RUT { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public decimal TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public Nullable<System.DateTime> FEC_NAC { get; set; }
        public Nullable<System.DateTime> FEC_CONTRATO { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public decimal ID_COMUNA { get; set; }
        public string RUT_EMP { get; set; }
        public decimal ID_STS { get; set; }
        public Nullable<decimal> ID_RUBRO { get; set; }
        public Nullable<decimal> ID_GENERO { get; set; }
        public Nullable<decimal> COD_CARGO { get; set; }
        public decimal ID_TIP_USER { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<CREDENCIAL> CREDENCIAL { get; set; }
        public virtual ICollection<DIR_DES_CLI> DIR_DES_CLI { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual RUBRO RUBRO { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_VENTA> USUARIO_VENTA { get; set; }
    }
}
