//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.USUARIO_VENTA = new HashSet<USUARIO_VENTA>();
            this.VENT_TIP_PAGO = new HashSet<VENT_TIP_PAGO>();
        }
    
        public decimal COD_VENTA { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FEC_VENTA { get; set; }
        public decimal ID_TIP_ENTREGA { get; set; }
        public decimal ID_TIP_COMPR { get; set; }
        public decimal ID_TIP_MONEY { get; set; }
        public string RUT_EMP { get; set; }
        public Nullable<decimal> COD_DIR { get; set; }
    
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual DIR_DESPACHO DIR_DESPACHO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPO_COMPROBANTE TIPO_COMPROBANTE { get; set; }
        public virtual TIPO_ENTREGA TIPO_ENTREGA { get; set; }
        public virtual TIPO_MONEDA TIPO_MONEDA { get; set; }
        public virtual ICollection<USUARIO_VENTA> USUARIO_VENTA { get; set; }
        public virtual ICollection<VENT_TIP_PAGO> VENT_TIP_PAGO { get; set; }
    }
}
